name: 🚀 12.2 Deploy

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

jobs:
  deploy:
    uses: ./.github/workflows/deploy.yml@main
    with:
      library: "12.2"
    secrets: inherit