name: 🚀 Deploy 12.2

on:
  workflow_dispatch:
  pull_request:
    branches:
      - '12.2'
  push:
    branches:
      - '12.2'

jobs:
  checks:
    uses: libhal/gnu-arm-embedded-toolchain/.github/workflows/deploy.yml@main
    secrets: inherit
